styria/styria/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'styria.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^zadatak/', include('zadatak.urls', namespace='zadatak')),
)

styria/zadatak/urls.py
from django.conf.urls import patterns, url

from zadatak import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'url_save/$', views.url_save, name='url_save'),
	url(r'url_process/$', views.url_process, name='url_process'),
	url(r'^(?P<url_id>\d+)/$', views.details, name='details'),
	)

styria/zadatak/models.py
from django.db import models

# Create your models here.
class Url(models.Model):
	url_data = models.URLField(max_length=400)
	status = models.BooleanField(default=False)
	def __unicode__(self):
		return self.url_data

class Words(models.Model):
	url = models.ForeignKey(Url)
	word = models.CharField(max_length=100, primary_key=True)
	def __unicode__(self):
		return self.word

class WordCount(models.Model):
	url = models.ForeignKey(Url)
	word = models.ForeignKey(Words)
	total = models.IntegerField(default=0)
	def __unicode__(self):
		return self.word
	def count(self):
		return self.total

styria/zadatak/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from zadatak.models import Url, Words, WordCount
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import transaction

import feedparser
import collections

# Create your views here.
def index(request):
	url_list = Url.objects.all()
	context = {"url_list": url_list}
	return render(request, 'zadatak/index.html', context)

def url_save(request):
	data = Url(url_data=request.POST['url_data'])
	data.save()
	return HttpResponseRedirect(reverse('zadatak:index'))

def url_process(request):
	not_empty = request.POST.getlist('cb')
	for x in Url.objects.all():
		x.status = False
		x.save()
	value = list()
	if request.POST and not_empty:
		for x in range(0, len(not_empty)):
			db_entry = Url.objects.get(pk=not_empty[x])
			db_entry.status = True
			db_entry.save()
			all_words = allWords(db_entry.url_data)
			# dio za spremanje jedinstvene rijeci u bazu
			singleWord(all_words, db_entry.id)
			value.append(db_entry)
		context = {"data": value}
		return render(request, 'zadatak/url_process.html', context)
	else:
		return HttpResponseRedirect(reverse('zadatak:index'))

def details(request, url_id):
	data = WordCount.objects.filter(url_id=url_id).order_by('-total')
	value = Url.objects.get(pk=url_id)
	paginator = Paginator(data, 30)
	page = request.GET.get('page')
	try:
		data = paginator.page(page)
	except PageNotAnInteger:
		data = paginator.page(1)
	except EmptyPage:
		data = paginator.page(paginator.num_pages)
	context = {"data": data, "value": value.url_data}
	#return render(request, 'zadatak/details.html', context)
	return render_to_response('zadatak/details.html', context)

def singleWord(all_words, url_id):
	#for x in Words.objects.all():
	#	x.delete()
	helper = list()
	for x in all_words:
		helper += x
	# odredivanje koliko se puta pojedina rijec pojavljuje
	# ovo je ujedno i dictionary s jedinstvenim rijecima
	word_count = collections.Counter(helper)
	# unique_word je da mogu referencirati dictionary word_count
	unique_word = list(set(helper))
	#sad to treba spremiti u bazu
	# ovaj dio je izuzetno spor, ali kad se ukljuci ovo
	# transaction.atomic() onda se ubrza
	with transaction.atomic():
                for x in word_count:
                        data = Words(url_id=url_id, word=x)
                        data.save()
                        data = WordCount(url_id=url_id, word_id=x, total=word_count.get(x))
                        data.save()
	return ()

def allWords(url):
	d = feedparser.parse(url)
	r_value = list()
	for x in d.entries:
		data = x.description
		text = ''.join(word if word.isalnum() else ' ' for word in data).split()
		# u text varijabli nalaze se sve rijeci za pojedini description
		r_value.append(text)
	#r_value je lista svih rijeci u svim descriptionima pojedinog feeda
	return r_value

styria/zadatak/templates/zadatak/details.html
<html>
<head>
	{% load staticfiles %}
		<link <link rel="stylesheet" type="text/css" href="{% static 'zadatak/style.css' %}" />
</head>
<body id="details-page">
	<h2>Rezultati za: <span>{{ value }}</span></h2>
	<a id="back" href="{% url 'zadatak:index' %}">back to index</a>
	<div id="details-wrapper">
		<ul>
		{% for x in data %}
			<li><label>{{ x.word }}</label> : <span>{{ x.total }}</span></li>
		{% endfor %}
		</ul>
	</div>
	<div class="pagination">
		<span class="step-links">
			{% if data.has_previous %}
				<a href="?page={{ data.previous_page_number }}">previous</a>
			{% endif %}
			<span class="current">
				page {{ data.number }} of {{ data.paginator.num_pages }}.
			</span>
			{% if data.has_next %}
				<a href="?page={{ data.next_page_number }}">next</a>
			{% endif %}
		</span>
	</div>
</body>
</html>

styria/zadatak/templates/zadatak/index.html
<html>
<head>
	{% load staticfiles %}
		<link <link rel="stylesheet" type="text/css" href="{% static 'zadatak/style.css' %}" />
</head>
<body id="index-page">
	<div id="new-url-wrapper">
		<h2>Add new rss feed</h2>
		<form id="new-url" name="new-url" action="{% url 'zadatak:url_save' %}" method="POST">
			{% csrf_token %}
			<input type="text" id="url_data" name="url_data" value="" placeholder="Please insert RSS feed url..." />
			<input id="button1" class="button" name="buton1" type="submit" value="Submit" />
		</form>
	</div>
	<div id="url-list-wrapper">
		<h2>List of all rss feeds</h2>
		<form id="url-list" name="url-list" action="{% url 'zadatak:url_process' %}" method="POST">
			{% csrf_token %}
			<ul>
				{% for data in url_list %}
				<li>
					<label>{{ data }}</label>
					<input id="cb-{{ data.id }}" class="checkbox"  name="cb" type="checkbox" value="{{ data.id }}" 
					{% if data.status == True %}
						checked
					{% endif %}
					/>
				</li>
				{% endfor %}
			</ul>
			<input id="button2" class="button" type="submit" value="Send" />
		</form>
	</div>
</body>
</html>

styria/zadatak/templates/zadatak/url_process.html
<html>
<head>
	{% load staticfiles %}
		<link <link rel="stylesheet" type="text/css" href="{% static 'zadatak/style.css' %}" />
</head>
<body id="process-page">
	<h2>Words were counted from these rss feeds</h2>
	<div id="process-wrapper">
		<ul>
			{% for x in data %}
				<li><a href="{% url 'zadatak:details' x.id %}">{{ x.url_data }}</a></li>
			{% endfor %}
		</ul>
	</div>
</body>
</html>